### PR TITLE
fix CI Github action

### PR DESCRIPTION
**Pull request by sub-mod**
https://github.com/mlperf/mlbox/issues/109

### CODE REVIEW

**Comment by sub-mod** [comment]
https://github.com/mlperf/mlbox/issues/115

**Comment by sergey-serebryakov** [comment]
I tested with several PRs and it worked. Just for my understanding. The CI steps run sequentially. MLCommons-Box is installed first. It is installed from the latest master branch, so it is always the latest version.   
Then, docker runner is installed:
```
cd runners/mlcommons_box_docker
pip install -r requirements.txt
python setup.py sdist bdist_wheel
```
What happens if it requires previous mlcommons-box version (step 2 above)? Is step 3 required?  
This is a little complicated, but something like this can work. When mlcommons-box is updated for the very first time after it was uploaded to pypi, increment its version in setup.py. Right after that, update `requirements.txt` of all runners - force them use this new mlcommons-box version. Idea is that in master branch, runners always required the latest mlcommons-box version.

**Comment by sub-mod** [comment]
>. The CI steps run sequentially. MLCommons-Box is installed first. It is installed from the latest master branch, so it is always the latest version.  

Yes, the latest code in github.

>previous mlcommons-box version (step 2 above)? Is step 3 required?

This has to be a new CI run. IMO Cannot be covered by this CI.

> increment its version in setup.py

This has to be a new CI run. We need a CI run for checking the latest & unchanged code too.

**Comment by sergey-serebryakov** [comment]
Current version of all libraries is `0.2.1` (defined in setup.py files). This is the current version of packages uploaded to [PyPi](https://pypi.org/search/?q=mlcommons-box&o=). 

Two libraries have been changed - core library and docker runner. Will versions be changed only for these two libraries or do we increment singularity/ssh versions as well?

**Comment by sergey-serebryakov** [comment]
I guess a separate PR is required to update versions.

**Comment by sergey-serebryakov** [comment]
As we discussed on Friday, the versions of libraries in master branch will always be the same, including python dependencies.  This PR solves the original problem and can be merged.

**Pull request merged**
