### PR TITLE
Refactor directories

### PR DESCRIPTION
**Pull request by swiftdiaries**
1. Plugin architecture for runners
1. Rename mlbox to mlcommons_box

### CODE REVIEW

**Comment by xyhuang** [comment]
>     1. I looked at the MNIST example, there's a `mlbox_docker.yaml` file (along with the `mlbox.yaml`) that species how MLBox is implemented. This information is loaded by the parser, so no need for now to provide runner name. Moving forward, however, I think we need to allow users to override the default mapping between MLBox implementation and reference runners to allow custom (user/corporate) runners.

the runner spec v0.1 proposes to move this docker config into `/platforms` directory, and user can specify their own platform config file during runtime which may partially or fully override the default config in the box, I think that will make it possible to override or add custom platforms/runners by the user.

>     2. We used to talk about `configure` / `run` actions previously. The `configure` is more generic than `build`, and for runners like Cloud runners or SSH runners using that name makes more sense. What do you think?

I'd like to suggest having both `configure` and `build` and using them for different purpose: the `build` may be used to create a box artifact that can run on a given platform (e.g. a container or VM image), while the `configure` may be used to interact with the platform itself to perform things like configurations and authentications, etc.

**Comment by xyhuang** [comment]
On a separate note, I'd also suggest that we have a `common` or `lib` directory under root that can be used to put shared libraries and tools. And we might also want an `examples` directory unless we are going to put the examples in a separate repo.

**Comment by sergey-serebryakov** [comment]
> I'd like to suggest having both `configure` and `build` and using them for different purpose: the `build` may be used to create a box artifact that can run on a given platform (e.g. a container or VM image), while the `configure` may be used to interact with the platform itself to perform things like configurations and authentications, etc.

I think it sort of makes sense. But at least now I am having difficulties in understanding if it results in fluent user experience. From a user point of view, how do they know when to use `configure`  and when to use `build`? Several examples:
- Local bare metal runner.
- Local docker/singularity containers.
- Remote coda bare metal environment.
- Remote docker/singularity containers.

According to current idea of chain of runners, supporting the above is not an issue. How do I know if the right command is `configure` or `build` if I do not know the implementation details (bare metal / docker)?

**Comment by bitfort** [comment]
One option is to put our common code in a pip package (mlcommons_box); and we have a different package for each runner, and our top level directories are pip packages.

**Comment by bitfort** [comment]
We would have the follow directories and each one is a pip package, which can depend on each other:
mlcommons_box (for shared dependencies and what is needed to make/vaidate a box)
mlbox_ssh_run (for running over ssh)
mlbox_docker_run (for running locally using docker)

**Comment by sub-mod** [comment]
LGTM thanks.

**Comment by swiftdiaries** [comment]
Thanks for the review and feedback y'all 😄

**Pull request merged**
